#!/bin/bash

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

export readonly DB_PATH="/app/app.db"

exec litestream replicate \
  -exec "/jbang/bin/jbang /app/Application.java"
  "${DB_PATH}" "${DB_REPLICA_URL}"